instabreak:
  - GRASS
  - TALL_GRASS
  - FERN
  - LARGE_FERN
  - DANDELION
  - POPPY
  - BLUE_ORCHID
  - ALLIUM
  - PINK_PETALS
  - AZURE_BLUET
  - OXEYE_DAISY
  - CORNFLOWER
  - RED_TULIP
  - ORANGE_TULIP
  - WHITE_TULIP
  - PINK_TULIP
  - SUNFLOWER
  - SWEET_BERRY_BUSH
  - WHEAT
  - CARROTS
  - POTATOES
  - BEETROOTS
  - BROWN_MUSHROOM
  - RED_MUSHROOM
  - MELON
  - PUMPKIN
  - SUGAR_CANE
  - CACTUS
  - BAMBOO
  - SEAGRASS
  - SEA_PICKLE
  - TUBE_CORAL_FAN
  - BRAIN_CORAL_FAN
  - BUBBLE_CORAL_FAN
  - FIRE_CORAL_FAN
  - HORN_CORAL_FAN
  - TUBE_CORAL
  - BRAIN_CORAL
  - BUBBLE_CORAL
  - FIRE_CORAL
  - HORN_CORAL
  - NETHER_SPROUTS
  - WARPED_FUNGUS
  - CRIMSON_FUNGUS
  - WARPED_ROOTS
  - CRIMSON_ROOTS
  - WITHER_ROSE
  - CHORUS_PLANT
  - CHORUS_FLOWER
  - FLOWERING_AZALEA